//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventionDiscovery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Invention
    {
        public int Id { get; set; }

        [StringLength(100, MinimumLength = 8)]
        [Required]
        public string InventorName { get; set; }

        [Required]
        public string ImagePath { get; set; }

        [Range(1400, 3000)]
        [Required]
        public string Year { get; set; }

        [Required]
        public string Country { get; set; }

        [Required]
        public string Biography { get; set; }

        [Required]
        public string InventionDiscovery { get; set; }

        [Required]
        public string Description { get; set; }
    }
}
